
genome: 'reference/genome.fa'
genome_lengths: 'reference/genome.lengths'
refseq: 'reference/refseq180404'
genes: 'cfg/genes.txt'
slop: 1000
samples: [
  'APCRC10N',
  'APCRC10T',
  'APCRC11N',
  'APCRC11T',
  'APCRC12N',
  'APCRC12T',
  'APCRC13N',
  'APCRC13T',
  'APCRC14N',
  'APCRC14T',
  'APCRC15N',
  'APCRC15T',
  'APCRC16N',
  'APCRC16T',
  'APCRC17N',
  'APCRC17T',
  'APCRC18N',
  'APCRC18T',
  'APCRC19N',
  'APCRC19T',
  'APCRC1N',
  'APCRC1T',
  'APCRC20N',
  'APCRC20T',
  'APCRC21N',
  'APCRC21T',
  'APCRC22N',
  'APCRC22T',
  'APCRC2N',
  'APCRC2T',
  'APCRC3N',
  'APCRC3T',
  'APCRC4N',
  'APCRC4T',
  'APCRC5N',
  'APCRC5T',
  'APCRC6N',
  'APCRC6T',
  'APCRC7N',
  'APCRC7T',
  'APCRC8N',
  'APCRC8T',
  'APCRC9N',
  'APCRC9T',
  'CMHS100',
  'CMHS101',
  'CMHS103',
  'CMHS104',
  'CMHS105',
  'CMHS106',
  'CMHS107',
  'CMHS108',
  'CMHS109',
  'CMHS110',
  'CMHS111',
  'CMHS112',
  'CMHS113',
  'CMHS114',
  'CMHS116',
  'CMHS117',
  'CMHS118',
  'CMHS119',
  'CMHS121',
  'CMHS122',
  'CMHS123',
  'CMHS124',
  'CMHS125',
  'CMHS126',
  'CMHS127',
  'CMHS128',
  'CMHS129',
  'CMHS130',
  'CMHS131',
  'CMHS132',
  'CMHS133',
  'CMHS134',
  'CMHS135',
  'CMHS136',
  'CMHS137',
  'CMHS138',
  'CMHS139',
  'CMHS140',
  'CMHS141',
  'CMHS142',
  'CMHS143',
  'CMHS144',
  'CMHS145',
  'CMHS146',
  'CMHS147',
  'CMHS148',
  'CMHS149',
  'CMHS150',
  'CMHS151',
  'CMHS152',
  'CMHS153',
  'CMHS154',
  'CMHS155',
  'CMHS156',
  'CMHS157',
  'CMHS158',
  'CMHS159',
  'CMHS15',
  'CMHS160',
  'CMHS161',
  'CMHS162',
  'CMHS163',
  'CMHS164',
  'CMHS165',
  'CMHS166',
  'CMHS167',
  'CMHS168',
  'CMHS169',
  'CMHS16',
  'CMHS170',
  'CMHS171',
  'CMHS172',
  'CMHS173',
  'CMHS174',
  'CMHS175',
  'CMHS176',
  'CMHS177',
  'CMHS178',
  'CMHS179',
  'CMHS17',
  'CMHS180',
  'CMHS181',
  'CMHS182',
  'CMHS183',
  'CMHS184',
  'CMHS185',
  'CMHS186',
  'CMHS187',
  'CMHS188',
  'CMHS189',
  'CMHS190',
  'CMHS191',
  'CMHS192',
  'CMHS193',
  'CMHS194',
  'CMHS195',
  'CMHS196',
  'CMHS197',
  'CMHS198',
  'CMHS199',
  'CMHS1',
  'CMHS200',
  'CMHS201',
  'CMHS202',
  'CMHS203',
  'CMHS204',
  'CMHS205',
  'CMHS206',
  'CMHS207',
  'CMHS208',
  'CMHS209',
  'CMHS20',
  'CMHS210',
  'CMHS211',
  'CMHS212',
  'CMHS213',
  'CMHS214',
  'CMHS215',
  'CMHS216',
  'CMHS217',
  'CMHS218',
  'CMHS219',
  'CMHS21',
  'CMHS220',
  'CMHS221',
  'CMHS222',
  'CMHS223',
  'CMHS224',
  'CMHS225',
  'CMHS226',
  'CMHS227',
  'CMHS228',
  'CMHS229',
  'CMHS22',
  'CMHS230',
  'CMHS231',
  'CMHS232',
  'CMHS233',
  'CMHS234',
  'CMHS235',
  'CMHS236',
  'CMHS237',
  'CMHS238',
  'CMHS239',
  'CMHS240',
  'CMHS241',
  'CMHS242',
  'CMHS243',
  'CMHS244',
  'CMHS245',
  'CMHS246',
  'CMHS247',
  'CMHS248',
  'CMHS249',
  'CMHS250',
  'CMHS251',
  'CMHS252',
  'CMHS253',
  'CMHS254',
  'CMHS255',
  'CMHS256',
  'CMHS257',
  'CMHS258',
  'CMHS259',
  'CMHS25',
  'CMHS260',
  'CMHS261',
  'CMHS262',
  'CMHS263',
  'CMHS264',
  'CMHS265',
  'CMHS266',
  'CMHS267',
  'CMHS268',
  'CMHS269',
  'CMHS26',
  'CMHS270',
  'CMHS271',
  'CMHS272',
  'CMHS273',
  'CMHS274',
  'CMHS275',
  'CMHS276',
  'CMHS277',
  'CMHS278',
  'CMHS279',
  'CMHS280',
  'CMHS281',
  'CMHS282',
  'CMHS283',
  'CMHS284',
  'CMHS285',
  'CMHS286',
  'CMHS287',
  'CMHS288',
  'CMHS289',
  'CMHS28',
  'CMHS290',
  'CMHS291',
  'CMHS292',
  'CMHS293',
  'CMHS294',
  'CMHS295',
  'CMHS296',
  'CMHS297',
  'CMHS298',
  'CMHS299',
  'CMHS29',
  'CMHS2',
  'CMHS300',
  'CMHS301',
  'CMHS302',
  'CMHS303',
  'CMHS304',
  'CMHS305',
  'CMHS306',
  'CMHS307',
  'CMHS308',
  'CMHS309',
  'CMHS310',
  'CMHS311',
  'CMHS312',
  'CMHS313',
  'CMHS314',
  'CMHS315',
  'CMHS316',
  'CMHS317',
  'CMHS318',
  'CMHS319',
  'CMHS320',
  'CMHS321',
  'CMHS322',
  'CMHS323',
  'CMHS324',
  'CMHS325',
  'CMHS326',
  'CMHS327',
  'CMHS328',
  'CMHS329',
  'CMHS32',
  'CMHS330',
  'CMHS331',
  'CMHS332',
  'CMHS333',
  'CMHS334',
  'CMHS335',
  'CMHS336',
  'CMHS337',
  'CMHS338',
  'CMHS339',
  'CMHS33',
  'CMHS340',
  'CMHS341',
  'CMHS342',
  'CMHS343',
  'CMHS344',
  'CMHS345',
  'CMHS346',
  'CMHS347',
  'CMHS348',
  'CMHS349',
  'CMHS350',
  'CMHS351',
  'CMHS352',
  'CMHS353',
  'CMHS354',
  'CMHS355',
  'CMHS356',
  'CMHS357',
  'CMHS358',
  'CMHS359',
  'CMHS35',
  'CMHS360',
  'CMHS361',
  'CMHS362',
  'CMHS363',
  'CMHS364',
  'CMHS365',
  'CMHS366',
  'CMHS367',
  'CMHS368',
  'CMHS369',
  'CMHS36',
  'CMHS370',
  'CMHS371',
  'CMHS372',
  'CMHS373',
  'CMHS374',
  'CMHS375',
  'CMHS376',
  'CMHS377',
  'CMHS37',
  'CMHS38',
  'CMHS39',
  'CMHS40',
  'CMHS41',
  'CMHS42',
  'CMHS43',
  'CMHS44',
  'CMHS45',
  'CMHS46',
  'CMHS47',
  'CMHS48',
  'CMHS49',
  'CMHS50',
  'CMHS51',
  'CMHS52',
  'CMHS53',
  'CMHS54',
  'CMHS55',
  'CMHS56',
  'CMHS57',
  'CMHS58',
  'CMHS59',
  'CMHS5',
  'CMHS60',
  'CMHS61',
  'CMHS62',
  'CMHS63',
  'CMHS64',
  'CMHS65',
  'CMHS66',
  'CMHS67',
  'CMHS68',
  'CMHS69',
  'CMHS6',
  'CMHS70',
  'CMHS71',
  'CMHS72',
  'CMHS73',
  'CMHS74',
  'CMHS75',
  'CMHS76',
  'CMHS77',
  'CMHS78',
  'CMHS79',
  'CMHS81',
  'CMHS82',
  'CMHS83',
  'CMHS85',
  'CMHS86',
  'CMHS87',
  'CMHS89',
  'CMHS90',
  'CMHS91',
  'CMHS92',
  'CMHS93',
  'CMHS94',
  'CMHS95',
  'CMHS96',
  'CMHS97',
  'CMHS98',
  'MINI51',
  'MINI52',
  'MINIA51']
